// Styles
import "./global.scss";
/* import type { Metadata } from 'next'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
} */

// React
import { ReactNode } from "react";

// Local Components
import Footer from "@/components/footer";
import Nav from "@/components/nav";

/*--------------------------------------------------------------------*/

/**
 * Component
 */

export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <html lang="en">
      {/* <body className={inter.className}>{children}</body> */}
      <body>
        <Nav />
        <main className="container-principal">{children}</main>
        <Footer />
      </body>
    </html>
  );
}
